#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 9a4613e7dab8 on Fri Apr 21 06:55:31 2017 from "/home/richie/mygit/LearningPy/wxGui/GUI/FormBarang.wxg"
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.CLOSE_BOX | wx.RESIZE_BORDER | wx.STAY_ON_TOP | wx.TAB_TRAVERSAL
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Form Data Barang"), style=wx.ALIGN_CENTER)
        self.text_ctrl_1 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_2 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_3 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.button_2 = wx.Button(self.panel_1, wx.ID_ANY, _("Ok"))
        self.button_1 = wx.Button(self.panel_1, wx.ID_ANY, _("Batal"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("frame"))
        self.SetSize((507, 662))
        self.label_4.SetFont(wx.Font(15, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Noto Sans"))
        self.text_ctrl_1.SetMinSize((360, 34))
        self.text_ctrl_2.SetMinSize((360, 34))
        self.text_ctrl_3.SetMinSize((360, 34))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        self.sizer_1 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_2 = wx.BoxSizer(wx.VERTICAL)
        self.grid_sizer_2 = wx.FlexGridSizer(1, 2, 0, 10)
        self.grid_sizer_1 = wx.FlexGridSizer(3, 2, 15, 10)
        self.sizer_2.Add(self.label_4, 0, wx.ALIGN_CENTER | wx.ALL, 15)
        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Kode Barang"))
        self.grid_sizer_1.Add(label_1, 1, wx.LEFT, 10)
        self.grid_sizer_1.Add(self.text_ctrl_1, 5, wx.RIGHT, 0)
        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Nama Barang"))
        self.grid_sizer_1.Add(label_2, 1, wx.LEFT, 10)
        self.grid_sizer_1.Add(self.text_ctrl_2, 5, 0, 0)
        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Satuan Barang"))
        self.grid_sizer_1.Add(label_3, 1, wx.LEFT, 10)
        self.grid_sizer_1.Add(self.text_ctrl_3, 5, 0, 0)
        self.grid_sizer_1.AddGrowableCol(1)
        self.grid_sizer_1.AddGrowableCol(2)
        self.sizer_2.Add(self.grid_sizer_1, 1, wx.EXPAND, 0)
        self.grid_sizer_2.Add(self.button_2, 0, wx.ALIGN_RIGHT | wx.BOTTOM | wx.TOP, 10)
        self.grid_sizer_2.Add(self.button_1, 0, wx.ALIGN_RIGHT | wx.BOTTOM | wx.RIGHT | wx.TOP, 10)
        self.grid_sizer_2.AddGrowableCol(0)
        self.grid_sizer_2.AddGrowableCol(1)
        self.sizer_2.Add(self.grid_sizer_2, 0, wx.ALIGN_RIGHT, 0)
        self.panel_1.SetSizer(self.sizer_2)
        self.sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(self.sizer_1)
        self.Layout()
        self.SetSize((507, 662))
        # end wxGlade

# end of class MyFrame
