// -*- C++ -*-
//
// generated by wxGlade 9a4613e7dab8 on Thu Apr 20 07:45:05 2017 from "/home/richie/mygit/LearningPy/wxGui/GUI/JendelaInti.wxg"
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef JENDELAINTI_H
#define JENDELAINTI_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "run"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
#include <wx/grid.h>
#include <wx/listctrl.h>
#include <wx/menu.h>
#include <wx/notebook.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class PanelJudul: public wxPanel {
public:
    // begin wxGlade: PanelJudul::ids
    // end wxGlade

    PanelJudul(wxWindow* parent, wxWindowID id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:
    // begin wxGlade: PanelJudul::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: PanelJudul::attributes
    wxStaticText* label_2;
    wxBoxSizer* sizer_2;
    // end wxGlade
}; // wxGlade: end class


class JendelaInti: public wxFrame {
public:
    // begin wxGlade: JendelaInti::ids
    // end wxGlade

    JendelaInti(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: JendelaInti::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: JendelaInti::attributes
    wxMenuBar* Menu;
    wxStatusBar* frame_statusbar;
    wxToolBar* frame_toolbar;
    PanelJudul* panel_judul;
    wxStaticBitmap* bitmap_2;
    wxPanel* Menu_Utama_copy;
    wxPanel* panel_8;
    wxPanel* panel_9;
    wxPanel* panel_10;
    wxTextCtrl* text_ctrl_5;
    wxTextCtrl* text_ctrl_6;
    wxButton* button_8;
    wxPanel* panel_11;
    wxPanel* panel_12;
    wxListCtrl* list_ctrl_2;
    wxButton* button_9;
    wxButton* button_2;
    wxButton* button_10;
    wxButton* button_11;
    wxButton* button_12;
    wxPanel* Penjualan_copy;
    wxGrid* grid_2;
    wxPanel* Data_Barang_copy;
    wxPanel* Data_Pekerja_copy;
    wxPanel* Pengaturan_copy;
    wxNotebook* notebook_2;
    wxPanel* panel_2;
    wxBoxSizer* sizer_3;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void keluar(wxCommandEvent &event); // wxGlade: <event_handler>
    void bantuan(wxCommandEvent &event); // wxGlade: <event_handler>
    void Input(wxCommandEvent &event); // wxGlade: <event_handler>
    void pilihan_lainnya(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // JENDELAINTI_H
