#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 9a4613e7dab8 on Wed Apr 19 07:22:24 2017 from "/home/richie/mygit/LearningPy/wxGui/GUI/JendelaInti.wxg"
#

import wx
import wx.grid

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class PanelJudul(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: PanelJudul.__init__
        wx.Panel.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: PanelJudul.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: PanelJudul.__do_layout
        self.sizer_2 = wx.BoxSizer(wx.VERTICAL)
        label_2 = wx.StaticText(self, wx.ID_ANY, _("APLIKASI PENJUALAN"), style=wx.ALIGN_CENTER)
        self.sizer_2.Add(label_2, 0, wx.ALIGN_CENTER | wx.EXPAND, 0)
        self.SetSizer(self.sizer_2)
        self.sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

# end of class PanelJudul

class JendelaInti(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: JendelaInti.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.Menu = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_item = wxglade_tmp_menu.Append(wx.ID_ANY, _("Keluar"), "")
        self.Bind(wx.EVT_MENU, self.keluar, id=wxglade_tmp_item.GetId())
        self.Menu.Append(wxglade_tmp_menu, _("Berkas"))
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, _("item"), "")
        self.Menu.Append(wxglade_tmp_menu, _("Pengaturan"))
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, _("Laporan"), "")
        self.Menu.Append(wxglade_tmp_menu, _("Lihat"))
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_item = wxglade_tmp_menu.Append(wx.ID_ANY, _("Bantuan"), "")
        self.Bind(wx.EVT_MENU, self.bantuan, id=wxglade_tmp_item.GetId())
        self.Menu.Append(wxglade_tmp_menu, _("Informasi"))
        self.SetMenuBar(self.Menu)
        # Menu Bar end
        self.frame_statusbar = self.CreateStatusBar(1)
        
        # Tool Bar
        self.frame_toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL | wx.TB_NOICONS | wx.TB_TEXT)
        self.SetToolBar(self.frame_toolbar)
        self.frame_toolbar.AddLabelTool(wx.ID_ANY, _("item"), wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddLabelTool(wx.ID_ANY, _("item"), wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddLabelTool(wx.ID_ANY, _("item"), wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddLabelTool(wx.ID_ANY, _("item"), wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddLabelTool(wx.ID_ANY, _("item"), wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        # Tool Bar end
        self.panel_judul = PanelJudul(self, wx.ID_ANY)
        self.panel_2 = wx.Panel(self, wx.ID_ANY)
        self.notebook_2 = wx.Notebook(self.panel_2, wx.ID_ANY, style=wx.NB_LEFT)
        self.Menu_Utama_copy = wx.Panel(self.notebook_2, wx.ID_ANY)
        self.bitmap_2 = wx.StaticBitmap(self.Menu_Utama_copy, wx.ID_ANY, wx.Bitmap("/home/richie/mygit/LearningPy/wxGui/GUI/images.png", wx.BITMAP_TYPE_ANY))
        self.Penjualan_copy = wx.Panel(self.notebook_2, wx.ID_ANY)
        self.panel_8 = wx.Panel(self.Penjualan_copy, wx.ID_ANY)
        self.panel_9 = wx.Panel(self.Penjualan_copy, wx.ID_ANY)
        self.panel_10 = wx.Panel(self.Penjualan_copy, wx.ID_ANY)
        self.panel_11 = wx.Panel(self.Penjualan_copy, wx.ID_ANY)
        self.text_ctrl_5 = wx.TextCtrl(self.panel_11, wx.ID_ANY, "")
        self.text_ctrl_6 = wx.TextCtrl(self.panel_11, wx.ID_ANY, _("1"), style=wx.TE_CENTRE)
        self.button_8 = wx.Button(self.panel_11, wx.ID_ADD, "")
        self.panel_12 = wx.Panel(self.Penjualan_copy, wx.ID_ANY)
        self.list_ctrl_2 = wx.ListCtrl(self.Penjualan_copy, wx.ID_ANY, style=wx.BORDER_DEFAULT | wx.BORDER_SUNKEN | wx.LC_REPORT | wx.NO_FULL_REPAINT_ON_RESIZE)
        self.button_9 = wx.Button(self.Penjualan_copy, wx.ID_ANY, _("Cetak & Simpan"))
        self.button_2 = wx.Button(self.Penjualan_copy, wx.ID_ANY, _("Cetak Saja"))
        self.button_10 = wx.Button(self.Penjualan_copy, wx.ID_ANY, _("Hapus"))
        self.button_11 = wx.Button(self.Penjualan_copy, wx.ID_ANY, _("Lihat"))
        self.button_12 = wx.Button(self.Penjualan_copy, wx.ID_ANY, _("Pilihan Lainnya"), style=wx.BU_EXACTFIT)
        self.Data_Barang_copy = wx.Panel(self.notebook_2, wx.ID_ANY)
        self.grid_2 = wx.grid.Grid(self.Data_Barang_copy, wx.ID_ANY, size=(1, 1))
        self.Data_Pekerja_copy = wx.Panel(self.notebook_2, wx.ID_ANY)
        self.Pengaturan_copy = wx.Panel(self.notebook_2, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.Input, self.button_8)
        self.Bind(wx.EVT_BUTTON, self.pilihan_lainnya, self.button_12)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: JendelaInti.__set_properties
        self.SetTitle(_("frame"))
        self.frame_statusbar.SetStatusWidths([-1])

        # statusbar fields
        frame_statusbar_fields = [_("Status")]
        for i in range(len(frame_statusbar_fields)):
            self.frame_statusbar.SetStatusText(frame_statusbar_fields[i], i)
        self.frame_toolbar.Realize()
        self.panel_9.SetBackgroundColour(wx.Colour(255, 255, 0))
        self.text_ctrl_5.SetMinSize((200, 34))
        self.button_9.SetMinSize((150, 34))
        self.button_2.SetMinSize((150, 34))
        self.button_10.SetMinSize((150, 34))
        self.button_11.SetMinSize((150, 34))
        self.button_12.SetMinSize((150, 34))
        self.grid_2.CreateGrid(10, 5)
        self.grid_2.EnableEditing(0)
        self.grid_2.SetColLabelValue(0, _("KODE BARANG"))
        self.grid_2.SetColSize(0, 150)
        self.grid_2.SetColLabelValue(1, _("NAMA BARANG"))
        self.grid_2.SetColSize(1, 300)
        self.grid_2.SetColLabelValue(2, _("SATUAN"))
        self.grid_2.SetColSize(2, 75)
        self.grid_2.SetColLabelValue(3, _(" HARGA\n SATUAN"))
        self.grid_2.SetColSize(3, 100)
        self.grid_2.SetColLabelValue(4, _("KETERANGAN"))
        self.grid_2.SetColSize(4, 300)
        self.grid_2.SetFocus()
        self.Data_Barang_copy.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.Data_Pekerja_copy.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.Pengaturan_copy.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.notebook_2.SetFont(wx.Font(13, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: JendelaInti.__do_layout
        self.sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_6 = wx.GridSizer(5, 1, 0, 0)
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_5 = wx.GridSizer(3, 3, 0, 0)
        grid_sizer_4 = wx.FlexGridSizer(1, 7, 0, 0)
        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_3.Add(self.panel_judul, 1, wx.EXPAND, 0)
        sizer_10.Add(self.bitmap_2, 2, wx.EXPAND, 0)
        self.Menu_Utama_copy.SetSizer(sizer_10)
        sizer_12.Add(self.panel_8, 0, 0, 0)
        label_7 = wx.StaticText(self.panel_9, wx.ID_ANY, _("0"), style=wx.ALIGN_CENTER | wx.ALIGN_RIGHT)
        label_7.SetFont(wx.Font(50, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        sizer_13.Add(label_7, 1, wx.ALIGN_RIGHT, 0)
        self.panel_9.SetSizer(sizer_13)
        sizer_12.Add(self.panel_9, 0, wx.EXPAND, 0)
        sizer_12.Add(self.panel_10, 0, 0, 0)
        label_8 = wx.StaticText(self.panel_11, wx.ID_ANY, _("Kode Barang"))
        grid_sizer_4.Add(label_8, 0, wx.ALIGN_CENTER | wx.LEFT, 8)
        grid_sizer_4.Add(self.text_ctrl_5, 0, wx.LEFT | wx.RIGHT, 8)
        label_9 = wx.StaticText(self.panel_11, wx.ID_ANY, _("Jumlah"))
        grid_sizer_4.Add(label_9, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_4.Add(self.text_ctrl_6, 0, wx.ALIGN_CENTER | wx.LEFT | wx.RIGHT, 8)
        grid_sizer_4.Add(self.button_8, 0, wx.RIGHT, 8)
        self.panel_11.SetSizer(grid_sizer_4)
        sizer_12.Add(self.panel_11, 0, wx.EXPAND, 0)
        grid_sizer_5.Add((0, 0), 0, 0, 0)
        grid_sizer_5.Add((0, 0), 0, 0, 0)
        grid_sizer_5.Add((0, 0), 0, 0, 0)
        grid_sizer_5.Add((0, 0), 0, 0, 0)
        grid_sizer_5.Add((0, 0), 0, 0, 0)
        grid_sizer_5.Add((0, 0), 0, 0, 0)
        grid_sizer_5.Add((0, 0), 0, 0, 0)
        grid_sizer_5.Add((0, 0), 0, 0, 0)
        grid_sizer_5.Add((0, 0), 0, 0, 0)
        self.panel_12.SetSizer(grid_sizer_5)
        sizer_12.Add(self.panel_12, 0, wx.EXPAND, 0)
        sizer_11.Add(sizer_12, 1, wx.EXPAND, 0)
        sizer_14.Add(self.list_ctrl_2, 5, wx.EXPAND, 0)
        grid_sizer_6.Add(self.button_9, 0, 0, 0)
        grid_sizer_6.Add(self.button_2, 0, 0, 0)
        grid_sizer_6.Add(self.button_10, 0, 0, 0)
        grid_sizer_6.Add(self.button_11, 0, 0, 0)
        grid_sizer_6.Add(self.button_12, 0, 0, 0)
        sizer_14.Add(grid_sizer_6, 1, wx.LEFT | wx.RIGHT, 10)
        sizer_11.Add(sizer_14, 5, wx.EXPAND, 0)
        self.Penjualan_copy.SetSizer(sizer_11)
        sizer_15.Add((0, 0), 0, 0, 0)
        sizer_15.Add(self.grid_2, 3, wx.EXPAND, 0)
        self.Data_Barang_copy.SetSizer(sizer_15)
        self.notebook_2.AddPage(self.Menu_Utama_copy, _("Menu Utama"))
        self.notebook_2.AddPage(self.Penjualan_copy, _("Penjualan"))
        self.notebook_2.AddPage(self.Data_Barang_copy, _("Data Barang"))
        self.notebook_2.AddPage(self.Data_Pekerja_copy, _("Data Pekerja"))
        self.notebook_2.AddPage(self.Pengaturan_copy, _("Pengaturan"))
        sizer_9.Add(self.notebook_2, 5, wx.ALIGN_CENTER | wx.EXPAND, 0)
        self.panel_2.SetSizer(sizer_9)
        self.sizer_3.Add(self.panel_2, 1, wx.EXPAND, 0)
        self.SetSizer(self.sizer_3)
        self.sizer_3.Fit(self)
        self.sizer_3.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade

    def keluar(self, event):  # wxGlade: JendelaInti.<event_handler>
        print("Event handler 'keluar' not implemented!")
        event.Skip()

    def bantuan(self, event):  # wxGlade: JendelaInti.<event_handler>
        print("Event handler 'bantuan' not implemented!")
        event.Skip()

    def Input(self, event):  # wxGlade: JendelaInti.<event_handler>
        print("Event handler 'Input' not implemented!")
        event.Skip()

    def pilihan_lainnya(self, event):  # wxGlade: JendelaInti.<event_handler>
        print("Event handler 'pilihan_lainnya' not implemented!")
        event.Skip()

# end of class JendelaInti
if __name__ == "__main__":
    gettext.install("run") # replace with the appropriate catalog name

    run = wx.PySimpleApp()
    JendelaInti = JendelaInti(None, wx.ID_ANY, "")
    run.SetTopWindow(JendelaInti)
    JendelaInti.Show()
    run.MainLoop()