# -*- coding: UTF-8 -*-
#
# generated by wxGlade aa26ff80e55e on Tue Mar 14 07:59:51 2017
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class JendelaKedua(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: JendelaKedua.__init__
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        
        # Tool Bar
        self.frame_1_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.frame_1_toolbar)
        # Tool Bar end
        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: JendelaKedua.__set_properties
        self.SetTitle(_("frame_1"))
        self.frame_1_toolbar.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: JendelaKedua.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        self.panel_1.SetSizer(sizer_5)
        sizer_2.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class JendelaKedua
