# -*- coding: UTF-8 -*-
#
# generated by wxGlade aa26ff80e55e on Tue Mar 14 08:00:48 2017
#

import wx
# begin wxGlade: dependencies
import wx.grid
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Layar3(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Layar3.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE | wx.TAB_TRAVERSAL
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_2_menubar = wx.MenuBar()
        self.Beranda = wx.Menu()
        item = self.frame_2_menubar.Keluar = wx.MenuItem(self.Beranda, 4, _("Keluar"), "", wx.ITEM_NORMAL)
        self.Beranda.AppendItem(self.frame_2_menubar.Keluar)
        self.Bind(wx.EVT_MENU, self.menu_keluar, id=item.GetId())
        self.frame_2_menubar.Append(self.Beranda, _("Beranda"))
        self.Pengaturan = wx.Menu()
        item = self.frame_2_menubar.Layar1 = wx.MenuItem(self.Pengaturan, 5, _("Layar1"), "", wx.ITEM_NORMAL)
        self.Pengaturan.AppendItem(self.frame_2_menubar.Layar1)
        self.Bind(wx.EVT_MENU, self.menu_layar1, id=item.GetId())
        item = self.frame_2_menubar.Layar2 = wx.MenuItem(self.Pengaturan, 6, _("Layar2"), "", wx.ITEM_NORMAL)
        self.Pengaturan.AppendItem(self.frame_2_menubar.Layar2)
        self.Bind(wx.EVT_MENU, self.menu_layar2, id=item.GetId())
        self.frame_2_menubar.Append(self.Pengaturan, _("Pengaturan"))
        self.Informasi = wx.Menu()
        item = self.frame_2_menubar.Pengembang = wx.MenuItem(self.Informasi, 7, _("Pengembang"), "", wx.ITEM_NORMAL)
        self.Informasi.AppendItem(self.frame_2_menubar.Pengembang)
        self.Bind(wx.EVT_MENU, self.menu_pengembang, id=item.GetId())
        item = self.frame_2_menubar.Bantuan = wx.MenuItem(self.Informasi, 8, _("Bantuan"), "", wx.ITEM_NORMAL)
        self.Informasi.AppendItem(self.frame_2_menubar.Bantuan)
        self.Bind(wx.EVT_MENU, self.menu_bantuan, id=item.GetId())
        self.frame_2_menubar.Append(self.Informasi, _("Informasi"))
        self.SetMenuBar(self.frame_2_menubar)
        # Menu Bar end
        
        # Tool Bar
        self.frame_2_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.frame_2_toolbar)
        # Tool Bar end
        self.panel_2 = wx.Panel(self, wx.ID_ANY)
        self.TabelNotebook1 = wx.Notebook(self.panel_2, wx.ID_ANY, style=wx.NB_LEFT)
        self.Barang = wx.Panel(self.TabelNotebook1, wx.ID_ANY)
        self.text_ctrl_1 = wx.TextCtrl(self.Barang, wx.ID_ANY, "")
        self.button_1 = wx.Button(self.Barang, wx.ID_ANY, _("Cari"), style=wx.BU_AUTODRAW)
        self.grid_1 = wx.grid.Grid(self.Barang, wx.ID_ANY, size=(1, 1))
        self.Penjualan = wx.Panel(self.TabelNotebook1, wx.ID_ANY)
        self.list_ctrl_1 = wx.ListCtrl(self.Penjualan, wx.ID_ANY, style=wx.BORDER_DEFAULT | wx.BORDER_SUNKEN | wx.LC_REPORT | wx.NO_FULL_REPAINT_ON_RESIZE)
        self.Bantuan = wx.Panel(self.TabelNotebook1, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.Yes, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Layar3.__set_properties
        self.SetTitle(_("Pos Penjualan"))
        self.SetSize((800, 601))
        self.frame_2_toolbar.Realize()
        self.button_1.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Noto Sans"))
        self.grid_1.CreateGrid(10, 3)
        self.grid_1.EnableEditing(0)
        self.grid_1.SetColLabelValue(0, _("Kode Barang"))
        self.grid_1.SetColSize(0, 150)
        self.grid_1.SetColLabelValue(1, _("Nama Barang"))
        self.grid_1.SetColSize(1, 300)
        self.grid_1.SetColLabelValue(2, _("Satuan"))
        self.grid_1.SetColSize(2, 100)
        self.TabelNotebook1.SetBackgroundColour(wx.Colour(204, 50, 50))
        self.TabelNotebook1.SetForegroundColour(wx.Colour(0, 0, 0))
        self.TabelNotebook1.SetFont(wx.Font(10, wx.DEFAULT, wx.ITALIC, wx.BOLD, 1, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Layar3.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.FlexGridSizer(2, 1, 0, 0)
        sizer_4 = wx.FlexGridSizer(1, 1, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_5 = wx.FlexGridSizer(3, 1, 0, 0)
        bagi_ruang_1 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_4 = wx.FlexGridSizer(1, 3, 0, 10)
        grid_sizer_3 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_3.Add((300, 0), 1, 0, 0)
        bitmap_1 = wx.StaticBitmap(self.panel_2, wx.ID_ANY, wx.Bitmap("/home/richie/Pictures/pmcicon.png", wx.BITMAP_TYPE_ANY))
        bitmap_1.SetMinSize((100, 100))
        grid_sizer_3.Add(bitmap_1, 0, 0, 0)
        grid_sizer_3.AddGrowableCol(0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        label_1 = wx.StaticText(self.Barang, wx.ID_ANY, _("Daftar Barang"), style=wx.ALIGN_CENTER)
        label_1.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Noto Sans"))
        bagi_ruang_1.Add(label_1, 0, wx.ALIGN_CENTER, 0)
        label_2 = wx.StaticText(self.Barang, wx.ID_ANY, _("Kode Barang"))
        label_2.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Noto Sans"))
        grid_sizer_4.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 11)
        grid_sizer_4.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)
        grid_sizer_4.Add(self.button_1, 1, wx.LEFT, 9)
        grid_sizer_4.AddGrowableCol(1)
        grid_sizer_4.AddGrowableCol(2)
        bagi_ruang_1.Add(grid_sizer_4, 1, wx.ALL | wx.EXPAND, 1)
        bagi_ruang_1.Add(self.grid_1, 1, wx.EXPAND, 0)
        self.Barang.SetSizer(bagi_ruang_1)
        bagi_ruang_1.AddGrowableRow(2)
        bagi_ruang_1.AddGrowableCol(0)
        label_3 = wx.StaticText(self.Penjualan, wx.ID_ANY, _("label_3"), style=wx.ALIGN_CENTER)
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_CENTER, 0)
        grid_sizer_5.Add((0, 0), 0, 0, 0)
        grid_sizer_5.Add(self.list_ctrl_1, 1, wx.EXPAND, 0)
        grid_sizer_5.Add((0, 0), 0, 0, 0)
        grid_sizer_5.AddGrowableRow(1)
        grid_sizer_5.AddGrowableCol(0)
        grid_sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)
        grid_sizer_1.Add((0, 0), 0, 0, 0)
        self.Penjualan.SetSizer(grid_sizer_1)
        grid_sizer_1.AddGrowableRow(1)
        self.TabelNotebook1.AddPage(self.Barang, _("Barang"))
        self.TabelNotebook1.AddPage(self.Penjualan, _("Penjualan"))
        self.TabelNotebook1.AddPage(self.Bantuan, _("Bantuan"))
        sizer_4.Add(self.TabelNotebook1, 1, wx.ALL | wx.EXPAND, 2)
        sizer_4.AddGrowableRow(0)
        sizer_4.AddGrowableCol(0)
        grid_sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        self.panel_2.SetSizer(grid_sizer_2)
        grid_sizer_2.AddGrowableRow(1)
        grid_sizer_2.AddGrowableCol(0)
        sizer_3.Add(self.panel_2, 1, wx.EXPAND | wx.FIXED_MINSIZE, 0)
        self.SetSizer(sizer_3)
        self.Layout()
        self.Centre()
        self.SetSize((800, 601))
        # end wxGlade

    def menu_keluar(self, event):  # wxGlade: Layar3.<event_handler>
        print("Event handler 'menu_keluar' not implemented!")
        event.Skip()

    def menu_layar1(self, event):  # wxGlade: Layar3.<event_handler>
        print("Event handler 'menu_layar1' not implemented!")
        event.Skip()

    def menu_layar2(self, event):  # wxGlade: Layar3.<event_handler>
        print("Event handler 'menu_layar2' not implemented!")
        event.Skip()

    def menu_pengembang(self, event):  # wxGlade: Layar3.<event_handler>
        print("Event handler 'menu_pengembang' not implemented!")
        event.Skip()

    def menu_bantuan(self, event):  # wxGlade: Layar3.<event_handler>
        print("Event handler 'menu_bantuan' not implemented!")
        event.Skip()

    def Yes(self, event):  # wxGlade: Layar3.<event_handler>
        print("Event handler 'Yes' not implemented!")
        event.Skip()

# end of class Layar3
