# -*- coding: UTF-8 -*-
#
# generated by wxGlade aa26ff80e55e on Tue Mar 14 08:00:48 2017
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Layar2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Layar2.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.list_ctrl_2 = wx.ListCtrl(self, wx.ID_ANY, style=wx.BORDER_DEFAULT | wx.LC_ICON | wx.LC_REPORT | wx.NO_FULL_REPAINT_ON_RESIZE)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Layar2.__set_properties
        self.SetTitle(_("frame"))
        self.SetSize((200, 200))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Layar2.__do_layout
        self.sizer_1 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_1.Add(self.list_ctrl_2, 1, wx.EXPAND, 0)
        self.SetSizer(self.sizer_1)
        self.Layout()
        self.Centre()
        self.SetSize((200, 200))
        # end wxGlade

# end of class Layar2
