#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade aa26ff80e55e on Tue Mar 14 08:32:56 2017
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from Layar1 import Layar1

class main(wx.App):
    def OnInit(self):
        frame_1 = Layar1(None, wx.ID_ANY, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return True

# end of class main

if __name__ == "__main__":
    gettext.install("pos") # replace with the appropriate catalog name

    pos = main(0)
    pos.MainLoop()