# -*- coding: UTF-8 -*-
#
# generated by wxGlade 9a4613e7dab8 on Thu Apr 13 12:51:52 2017
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class RangkaData(RangkaUtama):
    def __init__(self, *args, **kwds):
        # begin wxGlade: RangkaData.__init__
        RangkaUtama.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        
        # Tool Bar
        self.frame_1_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.frame_1_toolbar)
        # Tool Bar end
        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: RangkaData.__set_properties
        self.SetTitle(_("frame_1"))
        self.frame_1_toolbar.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: RangkaData.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        self.panel_1.SetSizer(sizer_5)
        sizer_2.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class RangkaData
