#! /usr/bin/env python
#
# Support module generated by PAGE version 4.8.9
# In conjunction with Tcl version 8.6
<<<<<<< HEAD
#    Mar 01, 2017 10:08:54 PM
=======
#    Mar 01, 2017 06:22:28 PM
>>>>>>> 58be5f9ec59c4f9183569d54f3b23562397fe242


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


<<<<<<< HEAD
def TODO():
    print('pythonmy_support.TODO')
    sys.stdout.flush()

=======
>>>>>>> 58be5f9ec59c4f9183569d54f3b23562397fe242
def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import pythonmy
    pythonmy.vp_start_gui()


