#############################################################################
# Generated by PAGE version 4.8.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top39
    namespace eval ::widgets::$base {
<<<<<<< HEAD
        set dflt,origin 1
        set runvisible 1
    }
    set site_3_0 $base.m40
    set site_3_0 $base.tFr41
    set site_5_0 .top39.tFr41.tNo44.pg0 
    set site_5_0 $site_5_0
    set site_5_1 .top39.tFr41.tNo44.pg1 
=======
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.m40
>>>>>>> 58be5f9ec59c4f9183569d54f3b23562397fe242
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top39 {base} {
    if {$base == ""} {
        set base .top39
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
<<<<<<< HEAD
        -menu "$top.m40" -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 605x454
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 1
=======
        -menu "$top.m40" -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 600x450+400+187
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
>>>>>>> 58be5f9ec59c4f9183569d54f3b23562397fe242
    wm maxsize $top 1265 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    menu $top.m40 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $top.m40 add cascade \
        -menu "$top.m40.men41" -activebackground {#d9d9d9} \
<<<<<<< HEAD
        -activeforeground {#000000} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label {Bilah utama} 
=======
        -activeforeground {#000000} -background {#d9d9d9} -command {} \
        -font TkMenuFont -foreground {#000000} -label {Bilah utama} 
>>>>>>> 58be5f9ec59c4f9183569d54f3b23562397fe242
    set site_3_0 $top.m40
    menu $site_3_0.men41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground black -tearoff 0 
    $site_3_0.men41 add command \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -command {# TODO} -font TkMenuFont \
        -foreground {#000000} -label Keluar/Exit 
<<<<<<< HEAD
    ttk::style configure TFrame -background #d9d9d9
    ttk::frame $top.tFr41 \
        -borderwidth 2 -relief groove -width 585 -height 435 
    vTcl:DefineAlias "$top.tFr41" "TFrame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr41
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $site_3_0.tNo44 \
        -width 562 -height 423 -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tNo44" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame .top39.tFr41.tNo44.pg0 -background #d9d9d9
    $site_3_0.tNo44 add .top39.tFr41.tNo44.pg0 \
        -padding 0 -sticky nsew -state normal -text {Page 1} -image {} \
        -compound none -underline -1 
    set site_5_0  $site_3_0.tNo44.pg0
    ttk::label $site_5_0.tLa45 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {No Id} 
    vTcl:DefineAlias "$site_5_0.tLa45" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    message $site_5_0.mes47 \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Formulir Pendaftaran} -width 413 
    vTcl:DefineAlias "$site_5_0.mes47" "Message1" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa48 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Nama Siswa} 
    vTcl:DefineAlias "$site_5_0.tLa48" "TLabel2" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_5_0.tLa49 \
        -background {#d9d9d9} -foreground {#000000} -relief flat \
        -text {Tempat,Tgl Lahir} 
    vTcl:DefineAlias "$site_5_0.tLa49" "TLabel3" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.tLa45 \
        -in $site_5_0 -x 20 -y 60 -width 137 -relwidth 0 -height 16 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.mes47 \
        -in $site_5_0 -x 70 -y 10 -width 413 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.tLa48 \
        -in $site_5_0 -x 20 -y 80 -anchor nw -bordermode ignore 
    place $site_5_0.tLa49 \
        -in $site_5_0 -x 20 -y 100 -anchor nw -bordermode ignore 
    frame .top39.tFr41.tNo44.pg1 -background #d9d9d9
    $site_3_0.tNo44 add .top39.tFr41.tNo44.pg1 \
        -padding 0 -sticky nsew -state normal -text {Page 2} -image {} \
        -compound none -underline -1 
    set site_5_1  $site_3_0.tNo44.pg1
    place $site_3_0.tNo44 \
        -in $site_3_0 -x 10 -y 5 -width 562 -relwidth 0 -height 423 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr41 \
        -in $top -x 10 -y 10 -width 585 -relwidth 0 -height 435 -relheight 0 \
        -anchor nw -bordermode ignore 
=======
    ###################
    # SETTING GEOMETRY
    ###################
>>>>>>> 58be5f9ec59c4f9183569d54f3b23562397fe242

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top39

