# -*- coding: UTF-8 -*-
#
# generated by wxGlade 9a4613e7dab8 on Fri Apr 14 19:51:15 2017
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class LayarUtama(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LayarUtama.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end
        
        # Tool Bar
        self.frame_toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL | wx.TB_TEXT)
        self.SetToolBar(self.frame_toolbar)
        self.frame_toolbar.AddLabelTool(1, _("namaku"), wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        # Tool Bar end
        self.frame_statusbar = self.CreateStatusBar(1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TOOL, self.tes, id=1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: LayarUtama.__set_properties
        self.SetTitle(_("APLIKASI PENJUALAN"))
        self.SetSize((400, 313))
        self.frame_toolbar.Realize()
        self.frame_statusbar.SetStatusWidths([-1])

        # statusbar fields
        frame_statusbar_fields = [_("frame_statusbar")]
        for i in range(len(frame_statusbar_fields)):
            self.frame_statusbar.SetStatusText(frame_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: LayarUtama.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add((0, 0), 0, 0, 0)
        sizer_2.Add((0, 0), 0, 0, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        self.Centre()
        self.SetSize((400, 313))
        # end wxGlade

    def tes(self, event):  # wxGlade: LayarUtama.<event_handler>
        print("Event handler 'tes' not implemented!")
        event.Skip()

# end of class LayarUtama
