# -*- coding: UTF-8 -*-
#
# generated by wxGlade 9a4613e7dab8 on Fri Apr 14 21:07:15 2017
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, wx.ID_ANY, style=wx.NB_LEFT)
        self.Menu_Utama = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.Penjualan = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.panel_2 = wx.Panel(self.Penjualan, wx.ID_ANY)
        self.text_ctrl_1 = wx.TextCtrl(self.Penjualan, wx.ID_ANY, "")
        self.button_2 = wx.Button(self.Penjualan, wx.ID_ADD, "")
        self.list_ctrl_1 = wx.ListCtrl(self.Penjualan, wx.ID_ANY, style=wx.BORDER_DEFAULT | wx.BORDER_SUNKEN | wx.LC_REPORT | wx.NO_FULL_REPAINT_ON_RESIZE)
        self.button_3 = wx.Button(self.Penjualan, wx.ID_ANY, "button_3")
        self.button_4 = wx.Button(self.Penjualan, wx.ID_ANY, "button_4")
        self.button_5 = wx.Button(self.Penjualan, wx.ID_ANY, "button_5")
        self.button_6 = wx.Button(self.Penjualan, wx.ID_ANY, "button_6")
        self.Data_Barang = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.Data_Pekerja = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.Pengaturan = wx.Panel(self.notebook_1, wx.ID_ANY)
        
        # Tool Bar
        self.frame_toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL | wx.TB_NOICONS | wx.TB_TEXT)
        self.SetToolBar(self.frame_toolbar)
        self.frame_toolbar.AddLabelTool(wx.ID_ANY, "item", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddLabelTool(wx.ID_ANY, "item", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddLabelTool(wx.ID_ANY, "item", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddLabelTool(wx.ID_ANY, "item", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_toolbar.AddLabelTool(wx.ID_ANY, "item", wx.NullBitmap, wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        # Tool Bar end
        
        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, "item", "")
        wxglade_tmp_menu.Append(wx.ID_ANY, "item", "")
        self.frame_menubar.Append(wxglade_tmp_menu, "item")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, "item", "")
        wxglade_tmp_menu.Append(wx.ID_ANY, "item", "")
        self.frame_menubar.Append(wxglade_tmp_menu, "item")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, "item", "")
        self.frame_menubar.Append(wxglade_tmp_menu, "item")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end
        self.frame_statusbar = self.CreateStatusBar(1)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.Input, self.button_2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame")
        self.SetSize((800, 366))
        self.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.Menu_Utama.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.panel_2.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.text_ctrl_1.SetMinSize((300, 34))
        self.button_3.SetMinSize((150, 34))
        self.button_4.SetMinSize((150, 34))
        self.button_5.SetMinSize((150, 34))
        self.button_6.SetMinSize((150, 34))
        self.Penjualan.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.Data_Barang.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.Data_Pekerja.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.Pengaturan.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.notebook_1.SetBackgroundColour(wx.Colour(159, 159, 95))
        self.frame_toolbar.Realize()
        self.frame_statusbar.SetStatusWidths([-1])

        # statusbar fields
        frame_statusbar_fields = ["Status"]
        for i in range(len(frame_statusbar_fields)):
            self.frame_statusbar.SetStatusText(frame_statusbar_fields[i], i)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2 = wx.GridSizer(4, 1, 0, 0)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(1, 3, 0, 0)
        label_2 = wx.StaticText(self, wx.ID_ANY, "APLIKASI PENJUALAN KASIR CANGGIH")
        label_2.SetBackgroundColour(wx.Colour(159, 159, 95))
        sizer_3.Add(label_2, 0, wx.ALIGN_CENTER, 0)
        sizer_6.Add(self.panel_2, 4, wx.EXPAND, 0)
        label_1 = wx.StaticText(self.Penjualan, wx.ID_ANY, "No Barcode")
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER | wx.LEFT | wx.RIGHT, 8)
        grid_sizer_1.Add(self.text_ctrl_1, 0, 0, 0)
        grid_sizer_1.Add(self.button_2, 0, wx.LEFT, 10)
        sizer_6.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_4.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_5.Add(self.list_ctrl_1, 5, wx.EXPAND, 0)
        grid_sizer_2.Add(self.button_3, 0, 0, 0)
        grid_sizer_2.Add(self.button_4, 0, 0, 0)
        grid_sizer_2.Add(self.button_5, 0, 0, 0)
        grid_sizer_2.Add(self.button_6, 0, 0, 0)
        sizer_5.Add(grid_sizer_2, 0, wx.LEFT | wx.RIGHT, 10)
        sizer_4.Add(sizer_5, 3, wx.EXPAND, 0)
        sizer_4.Add((0, 0), 0, 0, 0)
        self.Penjualan.SetSizer(sizer_4)
        self.notebook_1.AddPage(self.Menu_Utama, "Menu Utama")
        self.notebook_1.AddPage(self.Penjualan, "Penjualan")
        self.notebook_1.AddPage(self.Data_Barang, "Data Barang")
        self.notebook_1.AddPage(self.Data_Pekerja, "Data Pekerja")
        self.notebook_1.AddPage(self.Pengaturan, "Pengaturan")
        sizer_3.Add(self.notebook_1, 5, wx.ALIGN_CENTER | wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        self.Layout()
        self.Centre()
        self.SetSize((800, 366))
        # end wxGlade

    def Input(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'Input' not implemented!")
        event.Skip()

# end of class MyFrame
