# -*- coding: UTF-8 -*-
#
# generated by wxGlade 9a4613e7dab8 on Tue Apr 18 07:00:51 2017
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class tes(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: tes.__init__
        wx.Panel.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: tes.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: tes.__do_layout
        self.Layout()
        # end wxGlade

# end of class tes
