"""Subclass of MyFrame2, which is generated by wxFormBuilder."""

import wx
from Module import *

# Implementing MyFrame2
class MyFrame( frame.MyFrame2 ):
	def __init__( self, parent ):
		frame.MyFrame2.__init__( self, parent )
	
