"""Subclass of MyFrame, which is generated by wxFormBuilder."""

import wx
import frame

# Implementing MyFrame
class GuipythonMyFrame( frame.MyFrame ):
	def __init__( self, parent ):
		frame.MyFrame.__init__( self, parent )
	
