"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import tes

# Implementing MyFrame1
class tarik( tes.MyFrame1 ):
	def __init__( self, parent ):
		tes.MyFrame1.__init__( self, parent )
	
	# Handlers for MyFrame1 events.
	def m_button1OnButtonClick( self, event ):
            print "hello"
            pass	
