#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 9a4613e7dab8 on Wed Apr 26 11:49:08 2017 from "/home/richie/mygit/LearningPy/wxGui/Pulsa.wxg"
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.button_1 = wx.Button(self.panel_1, wx.ID_ANY, _("Pulsa Listrik"))
        self.button_2 = wx.Button(self.panel_1, wx.ID_ANY, _("Pulsa Handphone"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.pulsa_listrik, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.pulsa_handphone, self.button_2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("Pulsa Klik"))
        self.SetSize((1000, 500))
        self.button_1.SetMinSize((250, 250))
        self.button_1.SetFont(wx.Font(30, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Noto Sans"))
        self.button_1.SetDefault()
        self.button_2.SetMinSize((250, 250))
        self.button_2.SetFont(wx.Font(30, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Noto Sans"))
        self.button_2.SetDefault()
        self.panel_1.SetBackgroundColour(wx.Colour(122, 183, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_2 = wx.BoxSizer(wx.VERTICAL)
        self.grid_sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Pilihan Pembelian Pulsa"), style=wx.ALIGN_CENTER)
        label_1.SetFont(wx.Font(40, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Noto Sans"))
        self.sizer_2.Add(label_1, 0, wx.ALIGN_CENTER, 0)
        self.grid_sizer_1.Add(self.button_1, 1, wx.EXPAND, 0)
        self.grid_sizer_1.Add(self.button_2, 1, wx.EXPAND, 0)
        self.sizer_2.Add(self.grid_sizer_1, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(self.sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.SetSize((1000, 500))
        # end wxGlade

    def pulsa_listrik(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'pulsa_listrik' not implemented!")
        event.Skip()

    def pulsa_handphone(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'pulsa_handphone' not implemented!")
        event.Skip()

# end of class MyFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.App()
    frame = MyFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame)
    frame.Show()
    app.MainLoop()