#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade f1f66815ed4c on Fri Dec  2 09:32:18 2016
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.button_15 = wx.Button(self.panel_2, wx.ID_ANY, _("button_15"))
        self.button_12 = wx.Button(self.panel_2, wx.ID_ANY, _("button_12"))
        self.button_17 = wx.Button(self.panel_2, wx.ID_ANY, _("button_17"))
        self.button_18 = wx.Button(self.panel_2, wx.ID_ANY, _("button_18"))
        self.button_19 = wx.Button(self.panel_2, wx.ID_ANY, _("button_19"))
        self.button_20 = wx.Button(self.panel_2, wx.ID_ANY, _("button_20"))
        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("frame"))
        self.panel_1.SetMinSize((800, 400))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.FlexGridSizer(1, 2, 0, 0)
        self.grid_sizer_3 = wx.FlexGridSizer(1, 1, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(3, 2, 0, 0)
        grid_sizer_2.Add(self.button_15, 0, 0, 0)
        grid_sizer_2.Add(self.button_12, 0, 0, 0)
        grid_sizer_2.Add(self.button_17, 0, 0, 0)
        grid_sizer_2.Add(self.button_18, 0, 0, 0)
        grid_sizer_2.Add(self.button_19, 0, 0, 0)
        grid_sizer_2.Add(self.button_20, 0, 0, 0)
        self.panel_2.SetSizer(grid_sizer_2)
        grid_sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)
        grid_sizer_1.Add((0, 0), 0, 0, 0)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.grid_sizer_3.Add((0, 0), 0, 0, 0)
        self.panel_3.SetSizer(self.grid_sizer_3)
        sizer_2.Add(self.panel_3, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame
class MyApp(wx.App):
    def OnInit(self):
        frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(frame)
        frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = MyApp(0)
    app.MainLoop()
