#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade aa26ff80e55e on Sun Mar  5 08:02:38 2017
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class JendelaKedua(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: JendelaKedua.__init__
        wx.Frame.__init__(self, *args, **kwds)
        
        # Tool Bar
        self.frame_1_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.frame_1_toolbar)
        # Tool Bar end
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, _("Tutup"), "", wx.ITEM_NORMAL)
        self.Bind(wx.EVT_MENU, self.TutupAplikasi, id=item.GetId())
        self.frame_1_menubar.Append(wxglade_tmp_menu, _("Berkas"))
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, _("Buka Pengaturan"), "", wx.ITEM_NORMAL)
        self.Bind(wx.EVT_MENU, self.BukaPengaturan, id=item.GetId())
        self.frame_1_menubar.Append(wxglade_tmp_menu, _("Pengaturan"))
        wxglade_tmp_menu = wx.Menu()
        self.frame_1_menubar.Append(wxglade_tmp_menu, _("item"))
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end

        self.__set_properties()
        self.__do_layout()

        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: JendelaKedua.__set_properties
        self.SetTitle(_("frame_1"))
        self.SetSize((400, 300))
        self.frame_1_toolbar.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: JendelaKedua.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add((0, 0), 0, 0, 0)
        sizer_4.Add((0, 0), 0, 0, 0)
        sizer_4.Add((0, 0), 0, 0, 0)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        self.SetSize((400, 300))
        # end wxGlade

    def TutupAplikasi(self, event):  # wxGlade: JendelaKedua.<event_handler>
        app.Exit()
        print("Event handler 'TutupAplikasi' not implemented!")
        event.Skip()

    def BukaPengaturan(self, event):  # wxGlade: JendelaKedua.<event_handler>
        self.Buka=JendelaKesatu(None)
        self.Buka.Show(True)
        print("Event handler 'BukaPengaturan' not implemented!")
        event.Skip()

# end of class JendelaKedua

class JendelaKesatu(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: JendelaKesatu.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_2 = wx.Panel(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: JendelaKesatu.__set_properties
        self.SetTitle(_("frame_2"))
        self.SetSize((400, 300))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: JendelaKesatu.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(self.panel_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        self.Layout()
        self.SetSize((400, 300))
        # end wxGlade

# end of class JendelaKesatu
class MyApp(wx.App):
    def OnInit(self):
        frame_1 = JendelaKedua(None, wx.ID_ANY, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = MyApp(0)
    app.MainLoop()