#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade aa26ff80e55e on Tue Mar  7 13:08:48 2017
#

import wx
import wx.grid

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class JendelaKedua(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: JendelaKedua.__init__
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        
        # Tool Bar
        self.frame_1_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.frame_1_toolbar)
        # Tool Bar end
        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: JendelaKedua.__set_properties
        self.SetTitle(_("frame_1"))
        self.frame_1_toolbar.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: JendelaKedua.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        self.panel_1.SetSizer(sizer_5)
        sizer_2.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

# end of class JendelaKedua

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_3 = wx.Panel(self, wx.ID_ANY)
        self.notebook_2 = wx.Notebook(self.panel_3, wx.ID_ANY, style=wx.NB_LEFT)
        self.notebook_2_pane_1 = wx.Panel(self.notebook_2, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("frame"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.FlexGridSizer(1, 1, 0, 0)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        self.notebook_2.AddPage(self.notebook_2_pane_1, _("notebook_2_pane_1"))
        sizer_6.Add(self.notebook_2, 1, wx.EXPAND, 0)
        self.panel_3.SetSizer(sizer_6)
        sizer_1.Add(self.panel_3, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.AddGrowableRow(0)
        sizer_1.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

# end of class MyFrame

class MyFrame1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame1.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE | wx.TAB_TRAVERSAL
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_2 = wx.Panel(self, wx.ID_ANY)
        self.notebook_1 = wx.Notebook(self.panel_2, wx.ID_ANY, style=wx.NB_LEFT)
        self.Barang = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.text_ctrl_1 = wx.TextCtrl(self.Barang, wx.ID_ANY, "")
        self.button_1 = wx.Button(self.Barang, wx.ID_ANY, _("Cari"), style=wx.BU_AUTODRAW)
        self.grid_2 = wx.grid.Grid(self.Barang, wx.ID_ANY, size=(1, 1))
        self.Penjualan = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.Bantuan = wx.Panel(self.notebook_1, wx.ID_ANY)
        
        # Menu Bar
        self.frame_2_menubar = wx.MenuBar()
        self.SetMenuBar(self.frame_2_menubar)
        # Menu Bar end
        
        # Tool Bar
        self.frame_2_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.frame_2_toolbar)
        # Tool Bar end

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame1.__set_properties
        self.SetTitle(_("frame_2"))
        self.SetSize((773, 410))
        self.button_1.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Noto Sans"))
        self.grid_2.CreateGrid(23, 3)
        self.grid_2.SetRowLabelSize(20)
        self.grid_2.SetColLabelSize(25)
        self.grid_2.EnableEditing(0)
        self.grid_2.EnableDragColSize(0)
        self.grid_2.EnableDragRowSize(0)
        self.grid_2.EnableDragGridSize(0)
        self.grid_2.SetColLabelValue(0, _("Kode Barang"))
        self.grid_2.SetColSize(0, 175)
        self.grid_2.SetColLabelValue(1, _("Nama Barang"))
        self.grid_2.SetColSize(1, 300)
        self.grid_2.SetColLabelValue(2, _("Satuan"))
        self.notebook_1.SetBackgroundColour(wx.Colour(204, 50, 50))
        self.notebook_1.SetForegroundColour(wx.Colour(0, 0, 0))
        self.notebook_1.SetFont(wx.Font(10, wx.DEFAULT, wx.ITALIC, wx.BOLD, 1, ""))
        self.frame_2_toolbar.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame1.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_2 = wx.FlexGridSizer(2, 1, 0, 0)
        sizer_4 = wx.FlexGridSizer(1, 1, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_4 = wx.FlexGridSizer(1, 3, 0, 10)
        grid_sizer_3 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_3.Add((491, 0), 1, 0, 0)
        bitmap_1 = wx.StaticBitmap(self.panel_2, wx.ID_ANY, wx.Bitmap("/home/richie/Pictures/pmcicon.png", wx.BITMAP_TYPE_ANY))
        bitmap_1.SetMinSize((100, 100))
        grid_sizer_3.Add(bitmap_1, 0, 0, 0)
        grid_sizer_3.AddGrowableCol(0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        label_1 = wx.StaticText(self.Barang, wx.ID_ANY, _("Daftar Barang"), style=wx.ALIGN_CENTER)
        label_1.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Noto Sans"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER, 0)
        label_2 = wx.StaticText(self.Barang, wx.ID_ANY, _("Kode Barang"))
        label_2.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Noto Sans"))
        grid_sizer_4.Add(label_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 11)
        grid_sizer_4.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)
        grid_sizer_4.Add(self.button_1, 1, wx.LEFT, 9)
        grid_sizer_4.AddGrowableCol(1)
        grid_sizer_4.AddGrowableCol(2)
        grid_sizer_1.Add(grid_sizer_4, 1, wx.ALL | wx.EXPAND, 1)
        grid_sizer_1.Add(self.grid_2, 1, wx.EXPAND, 0)
        self.Barang.SetSizer(grid_sizer_1)
        grid_sizer_1.AddGrowableRow(2)
        grid_sizer_1.AddGrowableCol(0)
        self.notebook_1.AddPage(self.Barang, _("Barang"))
        self.notebook_1.AddPage(self.Penjualan, _("Penjualan"))
        self.notebook_1.AddPage(self.Bantuan, _("Bantuan"))
        sizer_4.Add(self.notebook_1, 1, wx.ALL | wx.EXPAND, 2)
        sizer_4.AddGrowableRow(0)
        sizer_4.AddGrowableCol(0)
        grid_sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        self.panel_2.SetSizer(grid_sizer_2)
        grid_sizer_2.AddGrowableRow(1)
        grid_sizer_2.AddGrowableCol(0)
        sizer_3.Add(self.panel_2, 1, wx.EXPAND | wx.FIXED_MINSIZE, 0)
        self.SetSizer(sizer_3)
        sizer_3.SetSizeHints(self)
        self.Layout()
        self.Centre()
        self.SetSize((773, 410))
        # end wxGlade

# end of class MyFrame1
if __name__ == "__main__":
    gettext.install("main") # replace with the appropriate catalog name

    main = wx.PySimpleApp()
    frame = MyFrame1(None, wx.ID_ANY, "")
    main.SetTopWindow(frame)
    frame.Show()
    main.MainLoop()