#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade aa26ff80e55e on Mon Mar  6 14:55:35 2017
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class JendelaKedua(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: JendelaKedua.__init__
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        
        # Tool Bar
        self.frame_1_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.frame_1_toolbar)
        # Tool Bar end
        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: JendelaKedua.__set_properties
        self.SetTitle(_("frame_1"))
        self.frame_1_toolbar.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: JendelaKedua.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add((0, 0), 0, 0, 0)
        sizer_5.Add((0, 0), 0, 0, 0)
        self.panel_1.SetSizer(sizer_5)
        sizer_2.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade

# end of class JendelaKedua

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("frame"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add((0, 0), 0, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyFrame

class Jendela(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Jendela.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, wx.ID_ANY, style=wx.NB_LEFT)
        self.Nb_utama = wx.Panel(self.notebook_1, wx.ID_ANY, style=wx.BORDER_STATIC | wx.TAB_TRAVERSAL)
        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Jendela.__set_properties
        self.SetTitle(_("frame_2"))
        self.SetSize((844, 614))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Jendela.__do_layout
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.GridSizer(1, 2, 0, 0)
        label_1 = wx.StaticText(self.Nb_utama, wx.ID_ANY, _("Aplikasi Buatan PMC Corps."))
        sizer_8.Add(label_1, 0, wx.ALIGN_CENTER, 0)
        bitmap_1 = wx.StaticBitmap(self.Nb_utama, wx.ID_ANY, wx.Bitmap("/home/richie/Pictures/pmcicon.png", wx.BITMAP_TYPE_ANY), style=wx.BORDER_STATIC)
        sizer_8.Add(bitmap_1, 0, wx.ALIGN_CENTER | wx.FIXED_MINSIZE | wx.SHAPED, 0)
        sizer_7.Add(sizer_8, 1, wx.EXPAND | wx.FIXED_MINSIZE, 0)
        label_2 = wx.StaticText(self.Nb_utama, wx.ID_ANY, _("Jl Raya Cicalengka RT 01 RW 11 Kp Margaasih\nKec Cicalengka. Kab Bandung. 40395"), style=wx.ALIGN_CENTER)
        sizer_7.Add(label_2, 0, wx.ALIGN_CENTER, 4)
        self.Nb_utama.SetSizer(sizer_7)
        self.notebook_1.AddPage(self.Nb_utama, _("Halaman Utama"))
        self.notebook_1.AddPage(self.notebook_1_pane_2, _("Penjualan"))
        sizer_6.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_6)
        sizer_6.SetSizeHints(self)
        self.Layout()
        self.SetSize((844, 614))
        # end wxGlade

# end of class Jendela
